
export default
{
    "problems": [
        {
            "title": "Multiples of 3 or 5",
            "id": 1,
            "active": true,
            "description": "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.  Find the sum of all the multiples of 3 or 5 below 1000.",
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Please enter a natural number...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'sumOfMultiplesOf3or5',
            "function": self.solutions['sumOfMultiplesOf3or5'],
            "result": null
        },
        {
            "title": "Even Fibonacci numbers",
            "id": 2,
            "active": false,
            "description": "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Please enter a natural number...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'sumOfEvenValuedFiboTerms',
            "function": self.solutions['sumOfEvenValuedFiboTerms'],
            "result": null
        },
        {
            "title": "Largest prime factor",
            "id": 3,
            "active": false,
            "description": "The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143 ?",
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Please enter a natural number...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'largestPrimeFactorOfN',
            "function": self.solutions['largestPrimeFactorOfN'],
            "result": null
        },
        {
            "title": "Largest palindrome product",
            "id": 4,
            "active": false,
            "description": "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two n-digit numbers.",
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Please enter number of digits...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'largestPalindromeFromProductOfNDigitnumbers',
            "function": self.solutions['largestPalindromeFromProductOfNDigitnumbers'],
            "result": null
        },
        {
            "title": "Smallest multiple",
            "id": 5,
            "active": false,
            "description": "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20 or 1 to n?",
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Please enter a natural number...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'smallestMultiple',
            "function": self.solutions['smallestMultiple'],
            "result": null
        },
        {
            "title": "Sum square difference",
            "id": 6,
            "active": false,
            "description": "The sum of the squares of the first ten natural numbers is 385. The square of the sum of the first ten natural numbers is 3025. Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 2640. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.",
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Please enter a natural number...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'differenceOfSumOfSquareAndSquareOfSum',
            "function": self.solutions['differenceOfSumOfSquareAndSquareOfSum'],
            "result": null

        },
        {
            "title": "10001st Prime",
            "id": 7,
            "active": false,
            "description": "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 10001st prime number?",
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Please enter a natural number...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'sieveOfEratosthenes',
            "function": self.solutions['sieveOfEratosthenes'],
            "result": null
        },
        {
            "title": "Largest product in a series",
            "id": 8,
            "active": false,
            "description": `
                <p>The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.</p>
                <p class="monospace center">
                73167176531330624919225119674426574742355349194934<br />
                96983520312774506326239578318016984801869478851843<br />
                85861560789112949495459501737958331952853208805511<br />
                12540698747158523863050715693290963295227443043557<br />
                66896648950445244523161731856403098711121722383113<br />
                62229893423380308135336276614282806444486645238749<br />
                30358907296290491560440772390713810515859307960866<br />
                70172427121883998797908792274921901699720888093776<br />
                65727333001053367881220235421809751254540594752243<br />
                52584907711670556013604839586446706324415722155397<br />
                53697817977846174064955149290862569321978468622482<br />
                83972241375657056057490261407972968652414535100474<br />
                82166370484403199890008895243450658541227588666881<br />
                16427171479924442928230863465674813919123162824586<br />
                17866458359124566529476545682848912883142607690042<br />
                24219022671055626321111109370544217506941658960408<br />
                07198403850962455444362981230987879927244284909188<br />
                84580156166097919133875499200524063689912560717606<br />
                05886116467109405077541002256983155200055935729725<br />
                71636269561882670428252483600823257530420752963450<br /></p>
                <p>Find the m adjacent digits in the n-digit number that have the greatest product. What is the value of this product?</p>
            `,
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Natural number to check...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'largeinput',
                    subtype: 'text',
                },
                {
                    name: 'm',
                    value: null,
                    comment: 'Number of adjacent digits to consider... ',
                    placeholder: 'Enter M...',
                    label: 'M',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'maxAdjacentDigitsProduct',
            "function": self.solutions['maxAdjacentDigitsProduct'],
            "result": null
        },
        {
            "title": "Special Pythagorean triplet",
            "id": 9,
            "active": false,
            "description": `
            <p>A Pythagorean triplet is a set of three natural numbers, <var>a</var> &lt; <var>b</var> &lt; <var>c</var>, for which,</p>
            <div class="center"> <var>a</var><sup>2</sup> + <var>b</var><sup>2</sup> = <var>c</var><sup>2</sup></div>
            <p>For example, 3<sup>2</sup> + 4<sup>2</sup> = 9 + 16 = 25 = 5<sup>2</sup>.</p>
            <p>There exists exactly one Pythagorean triplet for which <var>a</var> + <var>b</var> + <var>c</var> = 1000.<br />Find the product <var>abc</var>.</p>
            `,
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Enter a sum under which to check Special Triplet...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'pythagoreanTripletAddingToSum',
            "function": self.solutions['pythagoreanTripletAddingToSum'],
            "result": null
        },
        {
            "title": "Summation of Primes",
            "id": 10,
            "active": false,
            "description": "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17. Find the sum of all the primes below two million or below N.",
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Enter a number N below which sum of primes needed...  ',
                    placeholder: 'Enter N...',
                    label: 'N',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'sumOfAllPrimesBelowNum',
            "function": self.solutions['sumOfAllPrimesBelowNum'],
            "result": null
        },
        {
            "title": "Largest product in a grid",
            "id": 11,
            "active": false,
            "description": `
                <p>In the 20×20 grid below, four numbers along a diagonal line have been marked in red.</p>
                <p class="monospace center">
                08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08<br />
                49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00<br />
                81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65<br />
                52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91<br />
                22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80<br />
                24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50<br />
                32 98 81 28 64 23 67 10 <span class="red"><b>26</b></span> 38 40 67 59 54 70 66 18 38 64 70<br />
                67 26 20 68 02 62 12 20 95 <span class="red"><b>63</b></span> 94 39 63 08 40 91 66 49 94 21<br />
                24 55 58 05 66 73 99 26 97 17 <span class="red"><b>78</b></span> 78 96 83 14 88 34 89 63 72<br />
                21 36 23 09 75 00 76 44 20 45 35 <span class="red"><b>14</b></span> 00 61 33 97 34 31 33 95<br />
                78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92<br />
                16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57<br />
                86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58<br />
                19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40<br />
                04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66<br />
                88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69<br />
                04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36<br />
                20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16<br />
                20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54<br />
                01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48<br /></p>
                <p>The product of these numbers is 26 × 63 × 78 × 14 = 1788696.</p>
                <p>What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?</p>
            `,
            "inputs": [
                {
                    name: 'n',
                    value: null,
                    comment: 'Enter a number grid to compute...  ',
                    placeholder: 'Enter Number grid similar to above',
                    label: 'N',
                    type: 'largeinput',
                    subtype: 'text',
                },
                {
                    name: 'm',
                    value: null,
                    comment: 'Number of adjacent digits to consider... ',
                    placeholder: 'Enter M...',
                    label: 'M',
                    type: 'input',
                    subtype: 'number',
                },
            ],
            "functionName": 'productsInAGrid',
            "function": self.solutions['productsInAGrid'],
            "result": null
        },
        {
            "title": "Highly divisible triangular number",
            "id": 12,
            "active": false,
            "description": "The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be \
                            <br\><br\> 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ... \
                            <br\><br\> Let us list the factors of the first seven triangle numbers: \
                            <br\><br\> \
                            1: 1 \
                            <br\>3: 1,3 \
                            <br\>6: 1,2,3,6  \
                            <br\>10: 1,2,5,10 \
                            <br\>15: 1,3,5,15 \
                            <br\>21: 1,3,7,21 \
                            <br\>28: 1,2,4,7,14,28 \
                            <br\><br\> \
                            We can see that 28 is the first triangle number to have over five divisors.\
                            What is the value of the first triangle number to have over five hundred divisors?"
        },
        {
            "title": "Large sum",
            "id": 13,
            "active": false,
            "description": "Work out the first ten digits of the sum of the following one-hundred n-digit numbers."
        },
        {
            "title": "Longest Collatz sequence",
            "id": 14,
            "active": false,
            "description": `
                <p>The following iterative sequence is defined for the set of positive integers:</p>
                <p class="margin_left"><var>n</var> → <var>n</var>/2 (<var>n</var> is even)<br /><var>n</var> → 3<var>n</var> + 1 (<var>n</var> is odd)</p>
                <p>Using the rule above and starting with 13, we generate the following sequence:</p>
                <div class="center">13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1</div>
                <p>It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.</p>
                <p>Which starting number, under one million, produces the longest chain?</p>
                <p class="note"><b>NOTE:</b> Once the chain starts the terms are allowed to go above one million.</p>
            `
        },
        {
            "title": "Lattice paths",
            "id": 15,
            "active": false,
            "description": `
                <p>Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.</p>

                <p>How many such routes are there through a 20×20 grid?</p>
            `
        },
        {
            "title": "Power digit sum",
            "id": 16,
            "active": false,
            "description": `
                <p>2<sup>15</sup> = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.</p>
                <p>What is the sum of the digits of the number 2<sup>1000</sup>?</p>
            `
        },
        {
            "title": "Number letter counts",
            "id": 17,
            "active": false,
            "description": `
                <p>If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.</p>
                <p>If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used? </p>
                <br /><p class="note"><b>NOTE:</b> Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.</p>`
        },
        {
            "title": "Maximum path sum I",
            "id": 18,
            "active": false,
            "description": `
                <p>By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.</p>
                <p class="monospace center"><span class="red"><b>3</b></span><br /><span class="red"><b>7</b></span> 4<br />
                2 <span class="red"><b>4</b></span> 6<br />
                8 5 <span class="red"><b>9</b></span> 3</p>
                <p>That is, 3 + 7 + 4 + 9 = 23.</p>
                <p>Find the maximum total from top to bottom of the triangle below:</p>
                <p class="monospace center">75<br />
                95 64<br />
                17 47 82<br />
                18 35 87 10<br />
                20 04 82 47 65<br />
                19 01 23 75 03 34<br />
                88 02 77 73 07 63 67<br />
                99 65 04 28 06 16 70 92<br />
                41 41 26 56 83 40 80 70 33<br />
                41 48 72 33 47 32 37 16 94 29<br />
                53 71 44 65 25 43 91 52 97 51 14<br />
                70 11 33 28 77 73 17 78 39 68 17 57<br />
                91 71 52 38 17 14 91 43 58 50 27 29 48<br />
                63 66 04 68 89 53 67 30 73 16 69 87 40 31<br />
                04 62 98 27 23 09 70 98 73 93 38 53 60 04 23</p>
                <p class="note"><b>NOTE:</b> As there are only 16384 routes, it is possible to solve this problem by trying every route. However, <a href="problem=67">Problem 67</a>, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)</p>`
        },
        {
            "title": "Counting Sundays",
            "id": 19,
            "active": false,
            "description": `
                You are given the following information, but you may prefer to do some research for yourself.

                1 Jan 1900 was a Monday.
                Thirty days has September,
                April, June and November.
                All the rest have thirty-one,
                Saving February alone,
                Which has twenty-eight, rain or shine.
                And on leap years, twenty-nine.
                A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.
                How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?
            `
        },
        {
            "title": "Factorial digit sum",
            "id": 20,
            "active": false,
            "description": `<p><i>n</i>! means <i>n</i> × (<i>n</i> − 1) × ... × 3 × 2 × 1</p>
            <p>For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,<br />and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.</p>
            <p>Find the sum of the digits in the number 100!</p>
            `
        },
        {"title":"Amicable numbers",
        "id":21,
        "active":false,
        "description":`<p>Let d(<i>n</i>) be defined as the sum of proper divisors of <i>n</i> (numbers less than <i>n</i> which divide evenly into <i>n</i>).<br />
        If d(<i>a</i>) = <i>b</i> and d(<i>b</i>) = <i>a</i>, where <i>a</i> ≠ <i>b</i>, then <i>a</i> and <i>b</i> are an amicable pair and each of <i>a</i> and <i>b</i> are called amicable numbers.</p>
        <p>For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.</p>
        <p>Evaluate the sum of all the amicable numbers under 10000.</p>
        `},
        {"title":"Names scores",
        "id":22,
        "active":false,
        "description":`<p>Using <a href="project/resources/p022_names.txt">names.txt</a> (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.</p>
        <p>For example, when the list is sorted into alphabetical order, COLIN, which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 × 53 = 49714.</p>
        <p>What is the total of all the name scores in the file?</p>

        `},
        {"title":"Non-abundant sums",
        "id":23,
        "active":false,
        "description":`<p>A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of 28 would be 1 + 2 + 4 + 7 + 14 = 28, which means that 28 is a perfect number.</p>
        <p>A number <var>n</var> is called deficient if the sum of its proper divisors is less than <var>n</var> and it is called abundant if this sum exceeds <var>n</var>.</p>

        <p>As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.</p>
        <p>Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.</p>

        `},
        {"title":"Lexicographic permutations",
        "id":24,
        "active":false,
        "description":`<p>A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:</p>
        <p class="center">012   021   102   120   201   210</p>
        <p>What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?</p>

        `},
        {"title":"1000-digit Fibonacci number",
        "id":25,
        "active":false,
        "description":`<p>The Fibonacci sequence is defined by the recurrence relation:</p>
        <blockquote>F<sub><i>n</i></sub> = F<sub><i>n</i>−1</sub> + F<sub><i>n</i>−2</sub>, where F<sub>1</sub> = 1 and F<sub>2</sub> = 1.</blockquote>
        <p>Hence the first 12 terms will be:</p>
        <blockquote>F<sub>1</sub> = 1<br />
        F<sub>2</sub> = 1<br />
        F<sub>3</sub> = 2<br />
        F<sub>4</sub> = 3<br />
        F<sub>5</sub> = 5<br />
        F<sub>6</sub> = 8<br />
        F<sub>7</sub> = 13<br />
        F<sub>8</sub> = 21<br />
        F<sub>9</sub> = 34<br />
        F<sub>10</sub> = 55<br />
        F<sub>11</sub> = 89<br />
        F<sub>12</sub> = 144</blockquote>
        <p>The 12th term, F<sub>12</sub>, is the first term to contain three digits.</p>
        <p>What is the index of the first term in the Fibonacci sequence to contain 1000 digits?</p>

        `},
        {"title":"Reciprocal cycles",
        "id":26,
        "active":false,
        "description":`
        <p>A unit fraction contains 1 in the numerator. The decimal representation of the unit fractions with denominators 2 to 10 are given:</p>
        <blockquote>
        <table><tr><td><sup>1</sup>/<sub>2</sub></td><td>= </td><td>0.5</td>
        </tr><tr><td><sup>1</sup>/<sub>3</sub></td><td>= </td><td>0.(3)</td>
        </tr><tr><td><sup>1</sup>/<sub>4</sub></td><td>= </td><td>0.25</td>
        </tr><tr><td><sup>1</sup>/<sub>5</sub></td><td>= </td><td>0.2</td>
        </tr><tr><td><sup>1</sup>/<sub>6</sub></td><td>= </td><td>0.1(6)</td>
        </tr><tr><td><sup>1</sup>/<sub>7</sub></td><td>= </td><td>0.(142857)</td>
        </tr><tr><td><sup>1</sup>/<sub>8</sub></td><td>= </td><td>0.125</td>
        </tr><tr><td><sup>1</sup>/<sub>9</sub></td><td>= </td><td>0.(1)</td>
        </tr><tr><td><sup>1</sup>/<sub>10</sub></td><td>= </td><td>0.1</td>
        </tr></table></blockquote>
        <p>Where 0.1(6) means 0.166666..., and has a 1-digit recurring cycle. It can be seen that <sup>1</sup>/<sub>7</sub> has a 6-digit recurring cycle.</p>
        <p>Find the value of <i>d</i> &lt; 1000 for which <sup>1</sup>/<sub><i>d</i></sub> contains the longest recurring cycle in its decimal fraction part.</p>

        `},
        {"title":"Quadratic primes",
        "id":27,
        "active":false,
        "description":`<p>Euler discovered the remarkable quadratic formula:</p>
        <p class="center">$n^2 + n + 41$</p>
        <p>It turns out that the formula will produce 40 primes for the consecutive integer values $0 \le n \le 39$. However, when $n = 40, 40^2 + 40 + 41 = 40(40 + 1) + 41$ is divisible by 41, and certainly when $n = 41, 41^2 + 41 + 41$ is clearly divisible by 41.</p>
        <p>The incredible formula $n^2 - 79n + 1601$ was discovered, which produces 80 primes for the consecutive values $0 \le n \le 79$. The product of the coefficients, −79 and 1601, is −126479.</p>
        <p>Considering quadratics of the form:</p>
        <blockquote>
        $n^2 + an + b$, where $|a| &lt; 1000$ and $|b| \le 1000$<br /><br /><div>where $|n|$ is the modulus/absolute value of $n$<br />e.g. $|11| = 11$ and $|-4| = 4$</div>
        </blockquote>
        <p>Find the product of the coefficients, $a$ and $b$, for the quadratic expression that produces the maximum number of primes for consecutive values of $n$, starting with $n = 0$.</p>
        `},
        {"title":"Number spiral diagonals",
        "id":28,
        "active":false,
        "description":`<p>Starting with the number 1 and moving to the right in a clockwise direction a 5 by 5 spiral is formed as follows:</p>
        <p class="monospace center"><span class="red"><b>21</b></span> 22 23 24 <span class="red"><b>25</b></span><br />
        20  <span class="red"><b>7</b></span>  8  <span class="red"><b>9</b></span> 10<br />
        19  6  <span class="red"><b>1</b></span>  2 11<br />
        18  <span class="red"><b>5</b></span>  4  <span class="red"><b>3</b></span> 12<br /><span class="red"><b>17</b></span> 16 15 14 <span class="red"><b>13</b></span></p>
        <p>It can be verified that the sum of the numbers on the diagonals is 101.</p>
        <p>What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?</p>

        `},
        {"title":"Distinct powers",
        "id":29,
        "active":false,
        "description":`
        <p>Consider all integer combinations of <i>a</i><sup><i>b</i></sup> for 2 ≤ <i>a</i> ≤ 5 and 2 ≤ <i>b</i> ≤ 5:</p>
        <blockquote>2<sup>2</sup>=4, 2<sup>3</sup>=8, 2<sup>4</sup>=16, 2<sup>5</sup>=32<br />
        3<sup>2</sup>=9, 3<sup>3</sup>=27, 3<sup>4</sup>=81, 3<sup>5</sup>=243<br />
        4<sup>2</sup>=16, 4<sup>3</sup>=64, 4<sup>4</sup>=256, 4<sup>5</sup>=1024<br />
        5<sup>2</sup>=25, 5<sup>3</sup>=125, 5<sup>4</sup>=625, 5<sup>5</sup>=3125<br /></blockquote>
        <p>If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:</p>
        <p class="center">4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125</p>
        <p>How many distinct terms are in the sequence generated by <i>a</i><sup><i>b</i></sup> for 2 ≤ <i>a</i> ≤ 100 and 2 ≤ <i>b</i> ≤ 100?</p>

        `},

    ]
}